### ISSUE TITLE
[Crash] Exit Code -1 with Thingamajigs 1.7.1 (LockedDoor Mixin Incompatibility DramaticDoors)

### ISSUE THREAD

**Issue by adozenlionsroaring** [roberttkahelin8/thingmajigs#10]
I'm getting error "The game crashed whilst initializing game Error: java.lang.RuntimeException: null" with Exit Code -1. Minecraft version is 1.20.1, Forge version is 47.2.0 and Thingamajigs version is 1.7.1.

I have many, *many* other mods installed, so there is almost certainly a conflict happening somewhere. I've pasted the crash report here, which contains a list of the other mods: https://pastebin.com/nmBKiu18

Of particular relevance are these parts:

_"Suppressed: net.minecraftforge.fml.ModLoadingException: Thingamajigs (thingamajigs) encountered an error during the common_setup event phase
§7java.lang.IllegalArgumentException: Cannot set property BooleanProperty{name=waterlogged, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:air}"

"		at net.rk.thingamajigs.xtrablock.LockableDoor.<init>(LockableDoor.java:47) ~[thingamajigs-1.20.1-1.7.1.jar%23975!/:1.20.1-1.7.0] {re:classloading}
		at net.rk.thingamajigs.block.ThingamajigsBlocks.lambda$static$929(ThingamajigsBlocks.java:2262) ~[thingamajigs-1.20.1-1.7.1.jar%23975!/:1.20.1-1.7.0] {re:classloading}"_

**Comment by roberttkahelin8** [comment]
Another Note: ModernFix and Ferritecore usually are fine with Thingamajigs, and they are mentioning blockstate errors, so there is definitely some issue regarding a mixin that one of these 'door' mods is using. The dramatic doors mod is using a mixin to change how the doors works and how they are registered, which would break my mod indefinitely. I've never tested that mod with mine as I never thought it would work with my mod anyways. Seems like this might be true.

**Comment by roberttkahelin8** [comment]
One more major note: Remove my mod from your pack. If it still crashes, remove dramaticdoors. If it STILL crashes, something is very wrong.

**Comment by roberttkahelin8** [comment]
The fact the log is reporting that it cannot set a property on an air block means it didn't even have time to register the LockableDoor. Something before registries is messed up pretty badly: `§7java.lang.IllegalArgumentException: Cannot set property BooleanProperty{name=waterlogged, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:air}`

**Comment by roberttkahelin8** [comment]
For ref: Here is the 1.20.1 mixin for the door block that is conflicting with the LockableDoor: https://github.com/Kitteh6660/DramaticDoors/blob/1.20.1-quifabrge/forge/src/main/java/com/fizzware/dramaticdoors/forge/mixin/DoorBlockMixin.java

This may be part of the problem, but DramaticDoors will blame this mod as the issue causer so you don't want to report the issue there.

**Comment by adozenlionsroaring** [comment]
Thanks for confirming the source of the incompatibility! Yeah I've just tried disabling the waterlogging feature in the config file of Dramatic Doors but you're right, it doesn't help and the problem is much more fundamental than that.

That said, I've taken a look at the Dramatic Doors GitHub page and it seems the mod owners are quite open to compatibility suggestions, so I'll bring this up not as an issue but as a potential request...a patch to support the LockedDoor functionality of Thingamajigs may not be in the cards, but who knows? In the meantime, I'll forego Dramatic Doors while I try out your mod. Thanks again for your help! :)

(BTW, the Forgified Fabric API is used for the Sinytra Connector, allowing Fabric mods to be run on Forge. A few of the mods I've installed are Fabric only, like BetterEnd and BetterNether, so it's been a godsend!)

**Comment by roberttkahelin8** [comment]
Thank you for your crash report. It helps modders get things fixed up and more polished.

(I'll reopen the issue once a development on DramaticDoors occurs).

**Comment by Kitteh6660** [comment]
I will look into a fix for this!

**Comment by adozenlionsroaring** [comment]
It's all good - see my comment [here](https://github.com/Kitteh6660/DramaticDoors/issues/83#issuecomment-1974121546). :) Thanks again!

**Comment by roberttkahelin8** [comment]
@Kitteh6660 Just for clarification: I've tested the mod and its only crashing with waterlogging enabled. If that can be fixed somehow, fine, but if not, there is a workaround.

**Comment by Kitteh6660** [comment]
I will be adding Thingamajigs into the mod development environment and see if I can finally fix this issue for once and for all.

**Comment by Kitteh6660** [comment]
It turns out there is a simple culprit. The lockable door does not use super for defining block states, thus it does not inherit any additional properties like waterlogging.

So there are two solutions that can be done:

1. I will have to use a Mixin to manually inject waterlogging into LockableDoor.
2. Adjust this to use super, to inherit the properties, and add a line for locked property. https://github.com/roberttkahelin8/thingmajigs/blob/45c9fa2bfa4180794c1071e99104642026a88978/rawsrc/1.20.1/xtrablock/LockableDoor.java#L129
