### ISSUE TITLE
Awesome mod! A few requests:

### ISSUE THREAD

**Issue by CuddlesTheTiger** [roberttkahelin8/thingmajigs#11]
I've only been following this mod for maybe a year at most, and it's already come a long way. Just wanted to say how impressed I am with everything it has! I love using it in my 1.20.1 world. But there's also a few things I would love to see added if you're taking suggestions.

Conveyor Belt-
A slab that moves objects and mobs/players in a direction, much like the escalators

Fire Hydrant- 
Could come in three different colors, red, yellow, and silver. Possibly having a feature where you can open it and it will spawn a water source block next to it, and close it to get rid of it. 

Iron and Copper tables-
With the Iron/Copper block texture on top

Parking Meter-

Wall Clock-
Analog clock that tells in game time
something like this for design: https://mobileimages.lowes.com/productimages/dc316a39-7a91-4c19-abd4-bc0868e8e83a/62273370.jpg , could be round or square

changes to Grate block-
Could let liquids flow through it, but not solids

changes to gravestones-
If it's not much trouble, they could have text added to them like a sign

Thank you for taking these into consideration, I appreciate your hard work

**Comment by roberttkahelin8** [comment]
@CuddlesTheTiger thank you very much for your suggestions. They will be considered and some might even make it in the next update! ;) :D

**Comment by CuddlesTheTiger** [comment]
Thank you! I'm grateful for the reply!

As for your question on the grate blocks: Well if it's possible to not only waterlog it, but for water to be able to pass through it, I'd prefer that. But I'm struggling to think of other blocks that do that, unless they did add that to the Copper Grate recently.

I didn't see the Iron Table in the game, I have v1.7.1, but it's not showing up. There's chairs, but not the table
![2024-03-12_21 25 14](https://github.com/roberttkahelin8/thingmajigs/assets/162430122/7f465125-02b0-4ac8-82aa-f939b2c9fd7e)
