### ISSUE TITLE
Please add something related to construction

### ISSUE THREAD

**Issue by kazumadh** [roberttkahelin8/thingmajigs#13]
I installed your mod a few months ago and I'm now having a good time with it. However, for the better experience of your mod, I would like to express my ideas about what should be added, for example:
1. Concrete Blocks: There should be some variants of the texture, like grainy, brick or cobble
2. Steel Blocks: I recommend the texture to be seamless (no border)
3. Metal fence for under construction area: The color should be grey at the back and there should be some different colors for the front, the height can be adjusted by placing on each others.
4. AASHTO standard metal bridge railing: I suggest some types from the images below
**Images for illustration:**
_3.Metal fence construction:_ 
(back)![metal fence construction](https://github.com/roberttkahelin8/thingmajigs/assets/140326816/192a32b1-f309-40ee-9552-3cb363b4f0ba)
(front)
![119075894-two-panels-of-a-white-metal-fence-used-to-screen-off-a-wooded-site](https://github.com/roberttkahelin8/thingmajigs/assets/140326816/36ad7c8d-7605-4937-a096-3665c91e9e7f)
_4. AASHTO Bridge railing_
![2017 09 06-AMG-Metals-Railings-MTO-Railing-1](https://github.com/roberttkahelin8/thingmajigs/assets/140326816/6fc01f83-e6c3-44f3-844e-365a3857cd3a)
![Position-of-steel-parapet-railing-on-the-bridge-structure](https://github.com/roberttkahelin8/thingmajigs/assets/140326816/a513bddc-0edf-4208-8b97-9693a00e3d72)
![slide01](https://github.com/roberttkahelin8/thingmajigs/assets/140326816/234a4a8d-8969-4a5a-b1c0-4ffd823e3f91)
Looking forward to your response.

**Comment by roberttkahelin8** [comment]
Thanks for using Thingamajigs! Construction equipment is on a list of things that needed some attention but there is tons of it and many variants. Your suggestion is appreciated! Will try to add these in the coming updates.

**Comment by roberttkahelin8** [comment]
> I installed your mod a few months ago and I'm now having a good time with it. However, for the better experience of your mod, I would like to express my ideas about what should be added, for example:
> 
>     1. Concrete Blocks: There should be some variants of the texture, like grainy, brick or cobble
> 
>     2. Steel Blocks: I recommend the texture to be seamless (no border)
> 
>     3. Metal fence for under construction area: The color should be grey at the back and there should be some different colors for the front, the height can be adjusted by placing on each others.
> 
>     4. AASHTO standard metal bridge railing: I suggest some types from the images below
>        Looking forward to your response.

I sent a message without reply, oops! Could you perhaps add more details about Concrete Blocks and Steel Blocks (if you mean the existing Concrete Barriers or a new Concrete block with variants?). Also, perhaps a few more details on Steel Blocks (full block only? or perhaps variants?). And do you mean for the metal fence the first image is exactly how you want it to look? Its very repeatable with modeling work, which is a good thing, and do you want it to stack vertically like a connected pillar does). That's all. I'm certain I could figure it out, but a little more clarity always helps.

Note that in 1.7.3 cinder blocks are being added but there is no concrete block yet. 

But again thanks for the suggestion and helpful info!

**Comment by kazumadh** [comment]
> > I installed your mod a few months ago and I'm now having a good time with it. However, for the better experience of your mod, I would like to express my ideas about what should be added, for example:
> > ```
> > 1. Concrete Blocks: There should be some variants of the texture, like grainy, brick or cobble
> > 
> > 2. Steel Blocks: I recommend the texture to be seamless (no border)
> > 
> > 3. Metal fence for under construction area: The color should be grey at the back and there should be some different colors for the front, the height can be adjusted by placing on each others.
> > 
> > 4. AASHTO standard metal bridge railing: I suggest some types from the images below
> >    Looking forward to your response.
> > ```
> 
> I sent a message without reply, oops!
> 
> Could you perhaps add more details about Concrete Blocks and Steel Blocks (if you mean the existing Concrete Barriers or a new Concrete block with variants?).
> 
> Also, perhaps a few more details on Steel Blocks (full block only? or perhaps variants?).
> 
> And do you mean for the metal fence the first image is exactly how you want it to look? Its very repeatable with modeling work, which is a good thing, and do you want it to stack vertically like a connected pillar does).
> 
> That's all. I'm certain I could figure it out, but a little more clarity always helps.
> 
> Note that in 1.7.3 cinder blocks are being added (which aren't concrete per-say but idk, as all the research to find cool stuff to add kind of blurs.... oh well).
> 
> But again thanks for the suggestion and helpful info!

I'm talking about the whole new 1 x 1 x 1 concrete blocks, the same goes for the steel block.
Speaking of the metal fence, to be more precise, it's called "metal panel fence" or "hoarding metal fence". It can be supported at the back, or at the bottom (like the image shown below), or both. Stacking vertically to make it higher is the thing I mean.
![Hoarding-fence-UAE-500x400](https://github.com/roberttkahelin8/thingmajigs/assets/140326816/100a06e0-647a-483f-add3-d4774f4dbcca)

**Comment by roberttkahelin8** [comment]
> > > I installed your mod a few months ago and I'm now having a good time with it. However, for the better experience of your mod, I would like to express my ideas about what should be added, for example:
> > > ```
> > > 1. Concrete Blocks: There should be some variants of the texture, like grainy, brick or cobble
> > > 
> > > 2. Steel Blocks: I recommend the texture to be seamless (no border)
> > > 
> > > 3. Metal fence for under construction area: The color should be grey at the back and there should be some different colors for the front, the height can be adjusted by placing on each others.
> > > 
> > > 4. AASHTO standard metal bridge railing: I suggest some types from the images below
> > >    Looking forward to your response.
> > > ```
> > 
> > 
> > I sent a message without reply, oops!
> > Could you perhaps add more details about Concrete Blocks and Steel Blocks (if you mean the existing Concrete Barriers or a new Concrete block with variants?).
> > Also, perhaps a few more details on Steel Blocks (full block only? or perhaps variants?).
> > And do you mean for the metal fence the first image is exactly how you want it to look? Its very repeatable with modeling work, which is a good thing, and do you want it to stack vertically like a connected pillar does).
> > That's all. I'm certain I could figure it out, but a little more clarity always helps.
> > Note that in 1.7.3 cinder blocks are being added (which aren't concrete per-say but idk, as all the research to find cool stuff to add kind of blurs.... oh well).
> > But again thanks for the suggestion and helpful info!
> 
> I'm talking about the whole new 1 x 1 x 1 concrete blocks, the same goes for the steel block. Speaking of the metal fence, to be more precise, it's called "metal panel fence" or "hoarding metal fence". It can be supported at the back(like the image shown above), or at the bottom (like the image shown below), or both. Stacking vertically to make it higher is the thing I said. ![Hoarding-fence-UAE-500x400](https://private-user-images.githubusercontent.com/140326816/337508919-100a06e0-647a-483f-add3-d4774f4dbcca.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NjI3OTQsIm5iZiI6MTcxNzc2MjQ5NCwicGF0aCI6Ii8xNDAzMjY4MTYvMzM3NTA4OTE5LTEwMGEwNmUwLTY0N2EtNDgzZi1hZGQzLWQ0Nzc0ZjRkYmNjYS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDdUMTIxNDU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjUzN2E3MjZjOGMzODczMjJjNzIyOWVjNmM5MDg4OGFkZGZhZmRhOTFmNGZlOTE3NzgyODU2ZTBiOWViMWQwZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3HPHFEli6etDGHcWSdreekZqq99I_wAcqujtsaLHSto)

Got it. Thanks for the extra info!
